### ISSUE TITLE
[2.4.0] `apt-get install -y -q apt-transport-https` always executed

### ISSUE THREAD

**Issue by olblak** [DataDog/puppet-datadog-agent#491] opened 2019-01-25 08:54 UTC
It seems that this regression was introduced by this [commit](https://git.io/fhomI)
I am wondering why it changed from "ensure_packages" to a simple exec command?

**Comment by truthbk** [comment] 2019-01-29 10:08
Hi @olblak, thank you for taking the time to bring this up. Indeed this change was brought in here: https://github.com/DataDog/puppet-datadog-agent/pull/463. That PR was motivated by this issue: https://github.com/DataDog/puppet-datadog-agent/issues/423. 

We were actually aware of this new behavior, and though unhappy with the fact the module is now chatty, we merged it as a temporary workaround until we had a better understanding of how to fix the module in a more idiomatic way while avoiding triggering that nasty dependency cycle. Unfortunately the dependency cycle was not being caused by the module by itself, but rather by a behavior triggered when used in conjunction with other modules (definitely some versions of the logstash module, possibly others).

We are looking into a better workaround, for sure. If you have any suggestions please let us know.

**Comment by marcgascon** [comment] 2019-02-11 10:28
Hello, same issue here, we are having a lot of noise on every puppet run because of that.

I reviewed #463 PR and I don't see a clear answer of why ensure_packages was changed by an exec for apt-transport-https package installation. Can we rollback this part to ensure_packages again? 

If you want I can do the change, just let me know...

Thanks in advance 😄

**Comment by fr3nd** [comment] 2019-02-12 15:36
IMHO #463 should have never been merged... The 'workaround' is terrible: not only is verbose but it's running `apt-get install` on every puppet run! Please, consider the implications of running this on every instance where the datadog client is installed...

`ensure_packages` is the right way to do it even if it (in theory) causes issues with some specific module. Actually, even the puppetlabs/apt module is doing it that way: https://github.com/puppetlabs/puppetlabs-apt/blob/3c7229cde3234bef09ada611c98770269ff595a5/manifests/source.pp#L92

Has this issue been reported in any other module? Maybe the issue is not in the datadog module but in the logstash one.

**Comment by fr3nd** [comment] 2019-03-14 09:14
The package `apt-transport-https` is already installed by the `apt` module in case it's required (see https://github.com/puppetlabs/puppetlabs-apt/blob/3c7229cde3234bef09ada611c98770269ff595a5/manifests/source.pp#L92) since release 4.4.0.

The datadog puppet module requires the module apt, so enforcing the installation using the `exec` or even the `ensure_packages` function should not be required.

**Comment by truthbk** [comment] 2019-03-21 15:31
I merged this and reverted the module to the previous - correct - behavior: https://github.com/DataDog/puppet-datadog-agent/pull/506

We will address the problem for customers who might encounter cycle issues, as was the case with the old logstash module in some other way. I apologize for the inconvenience this has caused. The next version released should address this.

**Closed** 2019-03-22 16:14 UTC
